ALTER TABLE agencies
    ADD COLUMN stamp_path VARCHAR(512) DEFAULT NULL,
    ADD COLUMN stamp_x    FLOAT NOT NULL DEFAULT 380,
    ADD COLUMN stamp_y    FLOAT NOT NULL DEFAULT 690,
    ADD COLUMN stamp_w    FLOAT NOT NULL DEFAULT 150,
    ADD COLUMN stamp_h    FLOAT NOT NULL DEFAULT 80;
